#!/bin/bash

echo "Running server tests..." && \
./node_modules/.bin/babel-node ./node_modules/.bin/isparta cover --dir coverage/server ./node_modules/.bin/_mocha && \

echo -e "\nRunning client tests..." && \
./node_modules/.bin/babel-node ./node_modules/.bin/isparta cover --dir coverage/client ./node_modules/.bin/_mocha -- test/client/index.js && \

./node_modules/.bin/istanbul-combine -d coverage -r lcov -r html coverage/server/coverage.json coverage/client/coverage.json

exit $?
