#!/bin/bash
NYC="./node_modules/.bin/nyc --reporter=lcov"
MOCHA="./node_modules/.bin/_mocha --compilers js:babel-register -R dot"

$NYC bash -c "$MOCHA; $MOCHA test/client/index.js; $MOCHA test/browser/index.js"
exit $?
